import json
import os
from datetime import datetime

# Load report data
with open('/tmp/news-briefing-data.json', 'r') as f:
    data = json.load(f)

# Format Markdown
markdown = f"# News Briefing — {datetime.now().strftime('%Y-%m-%d')}\n\n"

sections = {
    "international": "International",
    "ireland": "Ireland",
    "netherlands": "Netherlands",
    "leiden": "Leiden & Local",
    "tech": "Tech",
    "gaming": "Gaming",
    "sre": "SRE / Infrastructure"
}

for key, title in sections.items():
    articles = data.get(key, [])
    if not articles and key == "sre":
        continue
    
    markdown += f"## {title}\n"
    if not articles:
        markdown += "- No news today in this section.\n\n"
        continue
        
    for a in articles:
        breaking_flag = "[BREAKING] " if a.get('breaking') else ""
        source_suffix = f" ({a['source']})" if a.get('source') else ""
        markdown += f"- **{breaking_flag}{a['title']}**{source_suffix} — {a['description']}\n"
        markdown += f"  {a['link']}\n\n"

# Save markdown to a file for the final output
with open('/tmp/report.md', 'w') as f:
    f.write(markdown)

# Build HTML Email
html = f"""<!DOCTYPE html>
<html>
<head><meta charset="utf-8"></head>
<body style="margin:0;padding:0;background:#f4f4f4;font-family:Arial,sans-serif;">
  <table width="100%" cellpadding="0" cellspacing="0" style="background:#f4f4f4;padding:24px 0;">
    <tr><td align="center">
      <table width="600" cellpadding="0" cellspacing="0" style="background:#ffffff;border-radius:8px;overflow:hidden;box-shadow:0 2px 8px rgba(0,0,0,0.08);">
        <tr><td style="background:#1a1a2e;padding:28px 32px;">
          <p style="margin:0;color:#a0a8c0;font-size:13px;letter-spacing:1px;text-transform:uppercase;">News Briefing</p>
          <h1 style="margin:4px 0 0;color:#ffffff;font-size:24px;">{datetime.now().strftime('%A, %b %d, %Y')}</h1>
        </td></tr>
"""

section_colors = {
    "international": ("#f5f0ff", "#8e44ad"),
    "ireland": ("#f0fff4", "#2ecc71"),
    "netherlands": ("#fff8f0", "#e67e22"),
    "leiden": ("#f0f4ff", "#4a6fa5"),
    "tech": ("#f0f7ff", "#3498db"),
    "gaming": ("#f5f0ff", "#9b59b6"),
    "sre": ("#fff5f5", "#e74c3c")
}

for key, title in sections.items():
    articles = data.get(key, [])
    if not articles and key == "sre":
        continue
    
    bg, border = section_colors.get(key, ("#f9f9f9", "#ccc"))
    
    html += f"""        <tr><td style="padding:24px 32px 0;">
          <h2 style="margin:0 0 12px;font-size:13px;font-weight:700;letter-spacing:1px;text-transform:uppercase;color:#1a1a2e;">{title}</h2>
"""
    if not articles:
        html += f"""          <p style="margin:0 0 10px;padding:10px 14px;background:#eee;border-left:3px solid #ccc;border-radius:4px;font-size:14px;color:#666;">No news today.</p>"""
    else:
        for a in articles:
            breaking_text = "[BREAKING] " if a.get('breaking') else ""
            source_html = f' <span style="color:{border};font-size:11px;font-weight:700;"> {a["source"]}</span>' if a.get('source') else ""
            html += f"""          <p style="margin:0 0 10px;padding:10px 14px;background:{bg};border-left:3px solid {border};border-radius:4px;font-size:14px;color:#333;">
            <a href="{a['link']}" style="color:#1a1a2e;text-decoration:none;font-weight:700;">{breaking_text}{a['title']}</a>{source_html}<br/>
            <span style="color:#666;font-size:13px;">{a['description']}</span>
          </p>
"""
    html += "        </td></tr>"

html += """        <tr><td style="padding:24px 32px;border-top:1px solid #eee;">
          <p style="margin:0;color:#aaa;font-size:12px;text-align:center;">Generated by your News Briefing Agent</p>
        </td></tr>
      </table>
    </td></tr>
  </table>
</body>
</html>
"""

with open('/tmp/report.html', 'w') as f:
    f.write(html)
